[metadata]
name = ptxsim-exec-ir-codegen
version = 0.0.1
description = PTXSim exec-IR code generation probe

[options]
python_requires = >=3.12
packages =
    ptxsim_exec_ir_codegen
    ptxsim_exec_ir_codegen.instructions
package_dir =
    ptxsim_exec_ir_codegen = codegen
    ptxsim_exec_ir_codegen.instructions = instructions
include_package_data = True
install_requires =
    ptx_frontend @ git+https://github.com/endingly/ptx_frontend.git@2e91093a2858a5902a92783f4aed93bebfa75afb#subdirectory=python

[options.package_data]
ptxsim_exec_ir_codegen.instructions =
    *.yaml

[options.entry_points]
console_scripts =
    ptxsim-exec-ir-codegen = ptxsim_exec_ir_codegen.cli:main
