"""Emit the selected fully-bound PTXSim execution instruction header."""

from __future__ import annotations

from ptx_frontend.base.utils import file_stem_to_pascal_case
from ptx_frontend.spec.model import OperandLayoutSpec

from .model import BackendSpec, SelectedForm, SelectedInstruction


def _variant_cpp_name(opcode: str, name: str) -> str:
    """Translate a normalized frontend variant id to its stable C++ name."""
    return file_stem_to_pascal_case(name.removeprefix(f"{opcode}_"))


def _layout_cpp_name(name: str) -> str:
    """Translate an operand-layout selector to a C++ nested record name."""
    return f"{file_stem_to_pascal_case(name)}Operands"


def _emit_layout(
    backend: BackendSpec,
    layout: OperandLayoutSpec,
    indent: str,
) -> list[str]:
    """Emit one operand record in normalized frontend operand order."""
    name = _layout_cpp_name(layout.name)
    lines = [
        f"{indent}/** @brief Operands selected by the `{layout.name}` layout. */",
        f"{indent}struct {name} {{",
    ]
    for operand in layout.operands:
        lines += [
            f"{indent}  /** @brief Fully-bound `{operand.role}` operand. */",
            f"{indent}  {backend.operand_kinds[operand.kind].cpp_type} "
            f"{operand.name};",
        ]
    return lines + [
        f"{indent}  /** @brief Compare fully-bound layout operands. */",
        f"{indent}  constexpr bool operator==(const {name}&) const noexcept "
        "= default;",
        f"{indent}}};",
    ]


def _emit_form(
    backend: BackendSpec,
    instruction: SelectedInstruction,
    form: SelectedForm,
) -> list[str]:
    """Emit one selected frontend variant with its modifiers and operands."""
    name = _variant_cpp_name(instruction.opcode, form.variant.name)
    lines = [
        f"  /** @brief Fully-bound `{form.variant.name}` instruction form. */",
        f"  struct {name} {{",
    ]
    for modifier in form.variant.modifiers:
        if modifier.presence == "absent":
            continue
        kind_mapping = backend.modifier_kinds[modifier.kind]
        if modifier.presence == "fixed":
            lines += [
                f"    /** @brief Fixed `{modifier.name}` selector required by "
                "this form. */",
                f"    inline static constexpr {kind_mapping.cpp_type} "
                f"{modifier.name} = {kind_mapping.cpp_value(modifier.value)};",
            ]
        else:
            lines += [
                f"    /** @brief Supported `{modifier.name}` selector copied "
                "from resolved IR. */",
                f"    {kind_mapping.cpp_type} {modifier.name};",
            ]
    if len(form.layouts) == 1 and len(form.variant.operand_layouts) == 1:
        for operand in form.layouts[0].operands:
            lines += [
                f"    /** @brief Fully-bound `{operand.role}` operand. */",
                f"    {backend.operand_kinds[operand.kind].cpp_type} "
                f"{operand.name};",
            ]
    else:
        for layout in form.layouts:
            lines += _emit_layout(backend, layout, "    ")
        alternatives = ", ".join(
            _layout_cpp_name(layout.name) for layout in form.layouts
        )
        lines += [
            "    /** @brief Operand-layout alternatives retained from the selected "
            "projection. */",
            f"    using Operands = std::variant<{alternatives}>;",
            "    /** @brief Operands bound according to the resolved layout. */",
            "    Operands operands;",
        ]
    return lines + [
        "    /** @brief Compare fully-bound form fields. */",
        f"    constexpr bool operator==(const {name}&) const noexcept = default;",
        "  };",
    ]


def header(
    backend: BackendSpec,
    selected: tuple[SelectedInstruction, ...],
) -> str:
    """Return a C++ header derived entirely from backend and frontend data."""
    classes = [file_stem_to_pascal_case(item.opcode) for item in selected]
    lines = [
        "// Generated by ptxsim_exec_ir_codegen. Do not edit.",
        "#pragma once",
        "",
        "#include <concepts>",
        "#include <cstdint>",
        "#include <optional>",
        "#include <type_traits>",
        "#include <variant>",
        "",
        "#include <ptxsim/exec_ir/exec_ir_types.hpp>",
        "",
        f"namespace {backend.namespace} {{",
        "",
        "/** @brief Pure execution opcode used by static executor dispatch. */",
        f"enum class Op : std::uint8_t "
        f"{{ {', '.join(item.opcode for item in selected)} }};",
        "",
    ]
    for instruction, class_name in zip(selected, classes, strict=True):
        lines += [
            f"/** @brief Fully-bound `{instruction.opcode}` execution instruction. */",
            f"struct {class_name} {{",
        ]
        for form in instruction.forms:
            lines += _emit_form(backend, instruction, form)
        alternatives = ", ".join(
            _variant_cpp_name(instruction.opcode, form.variant.name)
            for form in instruction.forms
        )
        lines += [
            "  /** @brief Selected frontend form for this opcode. */",
            f"  using Variant = std::variant<{alternatives}>;",
            "  /** @brief Predicate evaluated before this instruction observes "
            "operands. */",
            "  std::optional<Predicate> execution_predicate;",
            "  /** @brief Fully-bound selected form. */",
            "  Variant variant;",
            "  /** @brief Compare predicate and selected form. */",
            f"  constexpr bool operator==(const {class_name}&) const noexcept "
            "= default;",
            "};",
            "",
        ]
    alternatives = ", ".join(classes)
    concept = " || ".join(
        f"std::same_as<std::remove_cvref_t<T>, {name}>" for name in classes
    )
    lines += [
        "/** @brief Flat sum of executable opcode records. */",
        f"using Instruction = std::variant<{alternatives}>;",
        "/** @brief A type held by the generated execution instruction sum. */",
        "template <typename T>",
        f"concept InstructionAlternative = {concept};",
        "/** @brief Return the pure opcode independent of modifiers and operands. */",
        "[[nodiscard]] constexpr auto op(const Instruction& value) noexcept -> Op {",
        "  return std::visit([]<InstructionAlternative T>(const T&) constexpr {",
        *[
            f"    if constexpr (std::same_as<T, {name}>) "
            f"return Op::{instruction.opcode};"
            for instruction, name in zip(selected, classes, strict=True)
        ],
        "  }, value);",
        "}",
        "/** @brief Return the predicate stored by the selected opcode record. */",
        "[[nodiscard]] constexpr auto execution_predicate(const Instruction& value) "
        "-> const std::optional<Predicate>& {",
        "  return std::visit([]<InstructionAlternative T>(const T& item) "
        "-> const std::optional<Predicate>& { return item.execution_predicate; }, "
        "value);",
        "}",
        "/** @brief Report whether the selected opcode may advance to its "
        "successor PC. */",
        "[[nodiscard]] constexpr auto may_fallthrough(const Instruction& value) "
        "noexcept -> bool {",
        "  return std::visit([]<InstructionAlternative T>(const T& item) constexpr {",
        *[
            f"    if constexpr (std::same_as<T, {name}>) "
            f"return item.execution_predicate.has_value() || "
            f"{'true' if instruction.may_fallthrough else 'false'};"
            for instruction, name in zip(selected, classes, strict=True)
        ],
        "  }, value);",
        "}",
        "",
        f"}}  // namespace {backend.namespace}",
        "",
    ]
    return "\n".join(lines)
