if(NOT DEFINED PTXSIM_SNAPSHOT_DIR OR NOT DEFINED PTXSIM_PTX_FRONTEND_PORTFILE)
    message(FATAL_ERROR "PTXSIM_SNAPSHOT_DIR and PTXSIM_PTX_FRONTEND_PORTFILE are required")
endif()

set(manifest "${PTXSIM_SNAPSHOT_DIR}/SHA256SUMS")
set(provenance "${PTXSIM_SNAPSHOT_DIR}/README.md")
foreach(required IN ITEMS "${manifest}" "${provenance}" "${PTXSIM_PTX_FRONTEND_PORTFILE}")
    if(NOT EXISTS "${required}")
        message(FATAL_ERROR "Missing ptx_frontend snapshot input: ${required}")
    endif()
endforeach()

file(STRINGS "${manifest}" manifest_lines)
set(listed_files)
foreach(line IN LISTS manifest_lines)
    string(REGEX MATCH "^([0-9A-Fa-f]+)[ \t]+(.+)$" matched "${line}")
    if(NOT matched)
        message(FATAL_ERROR "Malformed SHA256SUMS line: ${line}")
    endif()
    set(expected_hash "${CMAKE_MATCH_1}")
    set(snapshot_file "${CMAKE_MATCH_2}")
    string(LENGTH "${expected_hash}" hash_length)
    if(NOT hash_length EQUAL 64 OR snapshot_file MATCHES "^/|(^|/)\\.\\.(/|$)")
        message(FATAL_ERROR "Invalid SHA256SUMS entry: ${line}")
    endif()
    list(FIND listed_files "${snapshot_file}" duplicate)
    if(NOT duplicate EQUAL -1)
        message(FATAL_ERROR "Duplicate SHA256SUMS entry: ${snapshot_file}")
    endif()
    if(NOT EXISTS "${PTXSIM_SNAPSHOT_DIR}/${snapshot_file}" OR
       IS_DIRECTORY "${PTXSIM_SNAPSHOT_DIR}/${snapshot_file}")
        message(FATAL_ERROR "Missing generated payload: ${snapshot_file}")
    endif()
    file(SHA256 "${PTXSIM_SNAPSHOT_DIR}/${snapshot_file}" actual_hash)
    string(TOLOWER "${expected_hash}" expected_hash)
    if(NOT actual_hash STREQUAL expected_hash)
        message(FATAL_ERROR "SHA256 mismatch for ${snapshot_file}")
    endif()
    list(APPEND listed_files "${snapshot_file}")
endforeach()

file(GLOB_RECURSE snapshot_files LIST_DIRECTORIES false
     RELATIVE "${PTXSIM_SNAPSHOT_DIR}" "${PTXSIM_SNAPSHOT_DIR}/*")
list(FILTER snapshot_files EXCLUDE REGEX "^(README\\.md|SHA256SUMS)$")
list(SORT listed_files)
list(SORT snapshot_files)
if(NOT "${listed_files}" STREQUAL "${snapshot_files}")
    message(FATAL_ERROR "SHA256SUMS does not exactly cover generated payloads")
endif()

file(STRINGS "${provenance}" provenance_lines REGEX "^`[0-9A-Fa-f]+`")
list(LENGTH provenance_lines provenance_count)
if(NOT provenance_count EQUAL 1)
    message(FATAL_ERROR "Generated provenance must contain exactly one revision")
endif()
string(REGEX MATCH "`([0-9A-Fa-f]+)`" matched "${provenance_lines}")
set(provenance_ref "${CMAKE_MATCH_1}")

file(STRINGS "${PTXSIM_PTX_FRONTEND_PORTFILE}" port_lines
     REGEX "^[ \t]*REF[ \t]+[0-9A-Fa-f]+")
list(LENGTH port_lines port_ref_count)
if(NOT port_ref_count EQUAL 1)
    message(FATAL_ERROR "ptx_frontend portfile must contain exactly one REF")
endif()
string(REGEX MATCH "REF[ \t]+([0-9A-Fa-f]+)" matched "${port_lines}")
set(port_ref "${CMAKE_MATCH_1}")
if(NOT provenance_ref STREQUAL port_ref)
    message(FATAL_ERROR "Generated provenance revision does not match portfile REF")
endif()
