#include <ptxsim/fp/environment.hpp>

#include <gtest/gtest.h>

#include <array>
#include <cstdint>

namespace ptxsim::fp::test {
namespace {

struct Bf16GoldenCase {
  char operation;
  std::uint16_t lhs;
  std::uint16_t rhs;
  RoundingMode rounding;
  std::uint16_t expected_bits;
  std::uint8_t expected_flags;
};

struct Bf16FmaGoldenCase {
  const char* label;
  std::uint16_t a;
  std::uint16_t b;
  std::uint16_t c;
  RoundingMode rounding;
  std::uint16_t expected_bits;
  std::uint8_t expected_flags;
};

// Generated by generate_bf16_golden.py using Fraction/integer arithmetic only;
// it is intentionally independent of both this implementation and SoftFloat.
constexpr std::array<Bf16GoldenCase, 62> kBf16GoldenCorpus{{
    {'a', 0x3F80u, 0x0000u, RoundingMode::NearestEven, 0x3F80u, 0x00u},
    {'a', 0x3F80u, 0x3F80u, RoundingMode::NearestEven, 0x4000u, 0x00u},
    {'a', 0xC000u, 0x3F00u, RoundingMode::NearestEven, 0xBFC0u, 0x00u},
    {'s', 0x3FC0u, 0x3F00u, RoundingMode::NearestEven, 0x3F80u, 0x00u},
    {'s', 0xBF80u, 0x3F00u, RoundingMode::NearestEven, 0xBFC0u, 0x00u},
    {'m', 0x3FC0u, 0x4000u, RoundingMode::NearestEven, 0x4040u, 0x00u},
    {'m', 0xBF80u, 0x3F80u, RoundingMode::NearestEven, 0xBF80u, 0x00u},
    {'a', 0x3F80u, 0x3B80u, RoundingMode::NearestEven, 0x3F80u, 0x01u},
    {'a', 0x3F80u, 0x3B80u, RoundingMode::TowardZero, 0x3F80u, 0x01u},
    {'a', 0x3F80u, 0x3B80u, RoundingMode::TowardNegative, 0x3F80u, 0x01u},
    {'a', 0x3F80u, 0x3B80u, RoundingMode::TowardPositive, 0x3F81u, 0x01u},
    {'a', 0xBF80u, 0xBB80u, RoundingMode::NearestEven, 0xBF80u, 0x01u},
    {'a', 0xBF80u, 0xBB80u, RoundingMode::TowardZero, 0xBF80u, 0x01u},
    {'a', 0xBF80u, 0xBB80u, RoundingMode::TowardNegative, 0xBF81u, 0x01u},
    {'a', 0xBF80u, 0xBB80u, RoundingMode::TowardPositive, 0xBF80u, 0x01u},
    {'m', 0x3F81u, 0x3F81u, RoundingMode::NearestEven, 0x3F82u, 0x01u},
    {'m', 0x3F81u, 0x3F81u, RoundingMode::TowardZero, 0x3F82u, 0x01u},
    {'m', 0x3F81u, 0x3F81u, RoundingMode::TowardNegative, 0x3F82u, 0x01u},
    {'m', 0x3F81u, 0x3F81u, RoundingMode::TowardPositive, 0x3F83u, 0x01u},
    {'m', 0xBF81u, 0x3F81u, RoundingMode::NearestEven, 0xBF82u, 0x01u},
    {'m', 0xBF81u, 0x3F81u, RoundingMode::TowardZero, 0xBF82u, 0x01u},
    {'m', 0xBF81u, 0x3F81u, RoundingMode::TowardNegative, 0xBF83u, 0x01u},
    {'m', 0xBF81u, 0x3F81u, RoundingMode::TowardPositive, 0xBF82u, 0x01u},
    {'a', 0x3F80u, 0x0001u, RoundingMode::NearestEven, 0x3F80u, 0x01u},
    {'a', 0x3F80u, 0x0001u, RoundingMode::TowardPositive, 0x3F81u, 0x01u},
    {'a', 0xBF80u, 0x8001u, RoundingMode::TowardNegative, 0xBF81u, 0x01u},
    {'a', 0x0001u, 0x0001u, RoundingMode::NearestEven, 0x0002u, 0x00u},
    {'a', 0x007Fu, 0x0001u, RoundingMode::NearestEven, 0x0080u, 0x00u},
    {'s', 0x0080u, 0x0001u, RoundingMode::NearestEven, 0x007Fu, 0x00u},
    {'m', 0x0001u, 0x3F00u, RoundingMode::NearestEven, 0x0000u, 0x03u},
    {'m', 0x0001u, 0x3F00u, RoundingMode::TowardPositive, 0x0001u, 0x03u},
    {'m', 0x8001u, 0x3F00u, RoundingMode::TowardNegative, 0x8001u, 0x03u},
    {'s', 0x3F80u, 0x3F80u, RoundingMode::NearestEven, 0x0000u, 0x00u},
    {'s', 0x3F80u, 0x3F80u, RoundingMode::TowardNegative, 0x8000u, 0x00u},
    {'a', 0x0000u, 0x8000u, RoundingMode::NearestEven, 0x0000u, 0x00u},
    {'a', 0x0000u, 0x8000u, RoundingMode::TowardNegative, 0x8000u, 0x00u},
    {'m', 0x8000u, 0x3F80u, RoundingMode::NearestEven, 0x8000u, 0x00u},
    {'m', 0x8000u, 0xBF80u, RoundingMode::NearestEven, 0x0000u, 0x00u},
    {'m', 0x7F7Fu, 0x4000u, RoundingMode::NearestEven, 0x7F80u, 0x05u},
    {'m', 0x7F7Fu, 0x4000u, RoundingMode::TowardZero, 0x7F7Fu, 0x05u},
    {'m', 0xFF7Fu, 0x4000u, RoundingMode::TowardNegative, 0xFF80u, 0x05u},
    {'a', 0x7F7Fu, 0x7F7Fu, RoundingMode::TowardPositive, 0x7F80u, 0x05u},
    {'a', 0x7F80u, 0x3F80u, RoundingMode::NearestEven, 0x7F80u, 0x00u},
    {'a', 0xFF80u, 0x3F80u, RoundingMode::NearestEven, 0xFF80u, 0x00u},
    {'a', 0x7F80u, 0xFF80u, RoundingMode::NearestEven, 0x7FC0u, 0x10u},
    {'s', 0x7F80u, 0x7F80u, RoundingMode::NearestEven, 0x7FC0u, 0x10u},
    {'m', 0x7F80u, 0xBF80u, RoundingMode::NearestEven, 0xFF80u, 0x00u},
    {'m', 0x7F80u, 0x0000u, RoundingMode::NearestEven, 0x7FC0u, 0x10u},
    {'m', 0xFF80u, 0x8000u, RoundingMode::NearestEven, 0x7FC0u, 0x10u},
    {'a', 0x7FC1u, 0x3F80u, RoundingMode::NearestEven, 0x7FC1u, 0x00u},
    {'a', 0x3F80u, 0xFFC2u, RoundingMode::NearestEven, 0xFFC2u, 0x00u},
    {'m', 0x7F82u, 0x3F80u, RoundingMode::NearestEven, 0x7FC2u, 0x10u},
    {'a', 0x7FC1u, 0x7F82u, RoundingMode::NearestEven, 0x7FC1u, 0x10u},
    {'s', 0x7F82u, 0x7FC1u, RoundingMode::NearestEven, 0x7FC2u, 0x10u},
    {'m', 0xFF82u, 0x7F80u, RoundingMode::NearestEven, 0xFFC2u, 0x10u},
    {'a', 0x0080u, 0x8080u, RoundingMode::TowardPositive, 0x0000u, 0x00u},
    {'a', 0x0080u, 0x8080u, RoundingMode::TowardNegative, 0x8000u, 0x00u},
    {'s', 0x0001u, 0x8001u, RoundingMode::NearestEven, 0x0002u, 0x00u},
    {'m', 0x007Fu, 0x3F81u, RoundingMode::NearestEven, 0x0080u, 0x01u},
    {'m', 0x007Fu, 0x3F81u, RoundingMode::TowardPositive, 0x0080u, 0x01u},
    {'a', 0x7E80u, 0x3F80u, RoundingMode::NearestEven, 0x7E80u, 0x01u},
    {'a', 0x0081u, 0x8080u, RoundingMode::NearestEven, 0x0001u, 0x00u},
}};

// Generated by generate_bf16_golden.py's independent Fraction oracle.
constexpr std::array<Bf16FmaGoldenCase, 28> kBf16FmaGoldenCorpus{{
    {"exact", 0x3F80u, 0x4000u, 0x3F80u, RoundingMode::NearestEven, 0x4040u, 0x00u},
    {"exact-negative", 0xBF80u, 0x4000u, 0xBF80u, RoundingMode::NearestEven, 0xC040u, 0x00u},
    {"halfway-ne", 0x3F81u, 0x3F81u, 0x0000u, RoundingMode::NearestEven, 0x3F82u, 0x01u},
    {"halfway-zero", 0x3F81u, 0x3F81u, 0x0000u, RoundingMode::TowardZero, 0x3F82u, 0x01u},
    {"halfway-negative", 0xBF81u, 0x3F81u, 0x0000u, RoundingMode::TowardNegative, 0xBF83u, 0x01u},
    {"halfway-positive", 0xBF81u, 0x3F81u, 0x0000u, RoundingMode::TowardPositive, 0xBF82u, 0x01u},
    {"midpoint-base", 0x3F82u, 0x3FA0u, 0x0000u, RoundingMode::NearestEven, 0x3FA2u, 0x01u},
    {"tiny-midpoint-double-rounding", 0x3F82u, 0x3FA0u, 0x0001u, RoundingMode::NearestEven, 0x3FA3u, 0x01u},
    {"subnormal-exact", 0x0001u, 0x3F80u, 0x0001u, RoundingMode::NearestEven, 0x0002u, 0x00u},
    {"subnormal-underflow", 0x0001u, 0x3F00u, 0x0000u, RoundingMode::NearestEven, 0x0000u, 0x03u},
    {"subnormal-directed", 0x8001u, 0x3F00u, 0x0000u, RoundingMode::TowardNegative, 0x8001u, 0x03u},
    {"overflow-ne", 0x7F7Fu, 0x4000u, 0x3F80u, RoundingMode::NearestEven, 0x7F80u, 0x05u},
    {"overflow-zero", 0x7F7Fu, 0x4000u, 0x3F80u, RoundingMode::TowardZero, 0x7F7Fu, 0x05u},
    {"cancel-plus-zero", 0x3F80u, 0x3F80u, 0xBF80u, RoundingMode::NearestEven, 0x0000u, 0x00u},
    {"cancel-minus-zero", 0x3F80u, 0x3F80u, 0xBF80u, RoundingMode::TowardNegative, 0x8000u, 0x00u},
    {"signed-zero-same", 0x8000u, 0x3F80u, 0x8000u, RoundingMode::NearestEven, 0x8000u, 0x00u},
    {"signed-zero-opposite", 0x8000u, 0x3F80u, 0x0000u, RoundingMode::TowardNegative, 0x8000u, 0x00u},
    {"qnan-a", 0x7FC1u, 0x3F80u, 0x3F80u, RoundingMode::NearestEven, 0x7FC1u, 0x00u},
    {"qnan-b", 0x3F80u, 0xFFC2u, 0x3F80u, RoundingMode::NearestEven, 0xFFC2u, 0x00u},
    {"qnan-c", 0x3F80u, 0x3F80u, 0xFFC3u, RoundingMode::NearestEven, 0xFFC3u, 0x00u},
    {"snan-a", 0x7F85u, 0x3F80u, 0x3F80u, RoundingMode::NearestEven, 0x7FC5u, 0x10u},
    {"snan-b", 0x3F80u, 0xFF86u, 0x3F80u, RoundingMode::NearestEven, 0xFFC6u, 0x10u},
    {"snan-c", 0x3F80u, 0x3F80u, 0x7F84u, RoundingMode::NearestEven, 0x7FC4u, 0x10u},
    {"inf-product", 0xFF80u, 0x3F80u, 0x3F80u, RoundingMode::NearestEven, 0xFF80u, 0x00u},
    {"inf-c", 0x3F80u, 0x3F80u, 0xFF80u, RoundingMode::NearestEven, 0xFF80u, 0x00u},
    {"inf-plus-opposite-inf", 0x7F80u, 0x3F80u, 0xFF80u, RoundingMode::NearestEven, 0x7FC0u, 0x10u},
    {"inf-zero", 0x7F80u, 0x0000u, 0x3F80u, RoundingMode::NearestEven, 0x7FC0u, 0x10u},
    {"inf-zero-cnan", 0x7F80u, 0x0000u, 0x7FC1u, RoundingMode::NearestEven, 0x7FC0u, 0x10u},
}};

}  // namespace

TEST(Bf16Arithmetic, IndependentFixedGoldenCorpus) {
  const Environment environment;
  for (const auto& golden : kBf16GoldenCorpus) {
    if (golden.rounding != RoundingMode::NearestEven)
      continue;  // The retained oracle also exercises the private packer.
    const auto control = ArithmeticControl{golden.rounding};
    const auto result = golden.operation == 'a'
                            ? environment.add(Bf16{golden.lhs}, Bf16{golden.rhs}, control)
                            : golden.operation == 's'
                                  ? environment.sub(Bf16{golden.lhs}, Bf16{golden.rhs}, control)
                                  : environment.mul(Bf16{golden.lhs}, Bf16{golden.rhs}, control);
    SCOPED_TRACE(::testing::Message()
                 << golden.operation << " lhs=0x" << std::hex << golden.lhs
                 << " rhs=0x" << golden.rhs);
    EXPECT_EQ(result.value.bits, golden.expected_bits);
    EXPECT_EQ(result.flags.bits(), golden.expected_flags);
  }
}

TEST(Bf16Arithmetic, IndependentExactFmaGoldenCorpus) {
  const Environment environment;
  for (const auto& golden : kBf16FmaGoldenCorpus) {
    if (golden.rounding != RoundingMode::NearestEven)
      continue;
    const auto result = environment.fma(
        Bf16{golden.a}, Bf16{golden.b}, Bf16{golden.c},
        ArithmeticControl{golden.rounding});
    SCOPED_TRACE(::testing::Message()
                 << golden.label << " a=0x" << std::hex << golden.a
                 << " b=0x" << golden.b << " c=0x" << golden.c);
    EXPECT_EQ(result.value.bits, golden.expected_bits);
    EXPECT_EQ(result.flags.bits(), golden.expected_flags);
  }
}

TEST(Bf16Arithmetic, AddSubMulAndRounding) {
  const Environment environment;
  EXPECT_EQ(environment.add(Bf16{0x3F80u}, Bf16{0x3F00u}).value.bits, 0x3FC0u);
  EXPECT_EQ(environment.sub(Bf16{0x3FC0u}, Bf16{0x3F00u}).value.bits, 0x3F80u);
  EXPECT_EQ(environment.mul(Bf16{0x3FC0u}, Bf16{0x4000u}).value.bits, 0x4040u);

  constexpr Bf16 one{0x3F80u};
  constexpr Bf16 half_ulp{0x3B80u};
  const auto nearest = environment.add(one, half_ulp);
  EXPECT_EQ(nearest.value.bits, one.bits);
  EXPECT_TRUE(nearest.flags.contains(ExceptionFlag::Inexact));
  EXPECT_THROW(static_cast<void>(environment.add(
                   one, half_ulp, {RoundingMode::TowardPositive})),
               std::invalid_argument);
}

TEST(Bf16Arithmetic, UnderflowOverflowSpecialsAndSignedZero) {
  const Environment environment;
  const auto underflow = environment.mul(Bf16{0x0001u}, Bf16{0x3F00u});
  EXPECT_EQ(underflow.value.bits, 0);
  EXPECT_TRUE(underflow.flags.contains(ExceptionFlag::Underflow));
  EXPECT_TRUE(underflow.flags.contains(ExceptionFlag::Inexact));

  const auto overflow = environment.mul(Bf16{0x7F7Fu}, Bf16{0x4000u});
  EXPECT_EQ(overflow.value.bits, 0x7F80u);
  EXPECT_TRUE(overflow.flags.contains(ExceptionFlag::Overflow));
  EXPECT_THROW(static_cast<void>(environment.mul(
                   Bf16{0x7F7Fu}, Bf16{0x4000u},
                   {RoundingMode::TowardZero})),
               std::invalid_argument);
  EXPECT_THROW(static_cast<void>(environment.sub(
                   Bf16{0x3F80u}, Bf16{0x3F80u},
                   {RoundingMode::TowardNegative})),
               std::invalid_argument);
  const auto signaling = environment.add(Bf16{0x7F81u}, Bf16{0x3F80u});
  EXPECT_TRUE(is_quiet_nan(signaling.value));
  EXPECT_TRUE(signaling.flags.contains(ExceptionFlag::Invalid));
  EXPECT_THROW(static_cast<void>(environment.add(Bf16{0x3F80u}, Bf16{0x3F80u},
                                                 {.flush_subnormal = true})),
               std::invalid_argument);
  EXPECT_THROW(static_cast<void>(environment.fma(Bf16{0x3F80u}, Bf16{0x3F80u},
                                                 Bf16{0x3F80u},
                                                 {.flush_subnormal = true})),
               std::invalid_argument);
}

}  // namespace ptxsim::fp::test
